apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qnhj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-qnhj@sha256:40d964104ad8206d90dd2576c1c9b100bbc69a450d3ff78527545f3da208996b
        name: my-nodejs
        resources: {}
status: {}
