apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qnhj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qnhj
    app.kubernetes.io/part-of: tkrw-pr712-0075-0004-app
  name: devfile-sample-qnhj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qnhj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qnhj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-qnhj@sha256:40d964104ad8206d90dd2576c1c9b100bbc69a450d3ff78527545f3da208996b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
